plugins {
    id 'buildlogic.java-common-conventions'
}

dependencies {
    implementation(project(':kwik')) // Add kwik core as a dependency
    implementation(project(':kwik-h09')) // Add kwik core as a dependency

    implementation "tech.kwik:agent15:$agent15_version"

    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    implementation 'commons-cli:commons-cli:1.11.0'
}

application {
    mainClass = 'tech.kwik.cli.KwikCli'
}

mavenPublishing {
    pom {
        name = 'Kwik Cli'
        description = 'Command line client for Kwik, the QUIC implementation in Java'
    }
}
