plugins {
    id 'buildlogic.java-common-conventions'
}

dependencies {
    implementation "tech.kwik:agent15:$agent15_version"

    implementation(project(':kwik')) // Add kwik core as a dependency

    // Default provider for Jakarta JSON Processing
    implementation 'org.eclipse.parsson:parsson:1.1.9'

    testImplementation(project(path: ':kwik', configuration: 'testArtifacts'))  // Necessary to use test utils from kwik core
}

mavenPublishing {
    pom {
        name = 'Kwik qlog'
        description = 'qlog add-on for Kwik, the QUIC implementation in Java'
    }
}
